//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tracnghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        public string MaThanhVien { get; set; }
        public int MaDeThi { get; set; }
        public long MaCauHoi { get; set; }
        public string DapAn { get; set; }
    
        public virtual CauHois CauHois { get; set; }
        public virtual DeThi DeThi { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
